version: '3.9'

services:
  web:
    build:
      context: ./apps/web
      dockerfile: dockerfile
      target: prod
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
    working_dir: /app
    command: bun dev --host 0.0.0.0

  api:
    build:
      context: ./apps/api
      dockerfile: dockerfile
      target: prod
    ports:
      - "8080:8080"
    volumes:
      - ./apps/api:/app
    working_dir: /app
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8080

volumes:
  web_node_modules:
